backend: 
  name: git-gateway
  branch: demo 

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
  #site_url: https://eloquent-visvesvaraya-619495.netlify.app/

collections:
  - name: "demo"
    label: "Demo"
    folder: "demo"
    create: true
    slug: "{{slug}}"
      # preview_path: "{{subfolder}}"
      # path: "{{subfolder}}/{{slug}}"
    nested: 
      depth: 100
    summary: "{{filename}}"
    extension: mdx
    format: frontmatter
    fields: 
     - {label: 'Subfolder', name: 'subfolder', widget: 'string'}
     - {label: "Sidebar Label", name: "sidebar_label", widget: "string", required: false}
     - {label: "Title", name: "title", widget: "string"}
     - {label: "ID", name: "id", widget: "string"}
     - {label: "Sidebar Position", name: "sidebar_position", widget: "number", value_type: "int", min: 0, required: false}
     - {label: "tags", name: "tags", widget: "list", default: ["demo"], required: false}
     - {label: "Body", name: "body", widget: "markdown", required: false}
    meta: {path: { label: 'Path', widget: 'string', index_file: '{{id}}' } }
