backend: 
  name: git-gateway
  branch: demo 

publish_mode: editorial_workflow
media_folder: "static/images"
public_folder: "/images"
  #site_url: https://eloquent-visvesvaraya-619495.netlify.app/

collections:
  - name: "demo"
    label: "Demo"
    folder: "/demo"
    create: true
    nested: 
      depth: 100
      summary: '{{title}}'
    slug: "{{slug}}"
    path: "{{fields.slug}}"
    summary: "{{filename}}"
    extension: mdx
    format: frontmatter
    fields: 
     - {label: "Slug" name: "slug", widget: "string"}
     - {label: "Sidebar Label", name: "sidebar_label", widget: "string"}
     - {label: "Title", name: "title", widget: "string"}
     - {label: "Sidebar Position", name: "sidebar_position", widget: "number", value_type: "int", min: 0}
     - {label: "tags", name: "tags", widget: "list", default: ["demo"]}
     - {label: "Body", name: "body", widget: "markdown"}


